
import useSWR from 'swr'; import { useState, useEffect } from 'react'; import TopNav from '../components/TopNav';
const f=(u)=>fetch(u).then(r=>r.json());
function getToken(){ try{ const raw=localStorage.getItem('estoque_srj_user'); if(!raw) return null; return JSON.parse(raw).token }catch(e){return null} }
export default function Usuarios(){ const {data,mutate}=useSWR('/api/users',f); const [username,setUsername]=useState(''); const [name,setName]=useState(''); const [password,setPassword]=useState(''); const [role,setRole]=useState('usuario'); const [myRole,setMyRole]=useState(null); useEffect(()=>{ (async ()=>{ const res=await fetch('/api/users/me',{ headers: { Authorization: 'Bearer '+getToken() } }); if(res.ok){ const j=await res.json(); setMyRole(j.role) } })() },[]);
  const add=async()=>{ await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,name,password,role})}); setUsername(''); setName(''); setPassword(''); setRole('usuario'); mutate(); }
  const remove=async(usernameToDelete)=>{ if(!confirm('Excluir usuário?')) return; const token = getToken(); if(!token) return alert('Sem permissão'); const res=await fetch('/api/users/'+encodeURIComponent(usernameToDelete), { method: 'DELETE', headers: { Authorization: 'Bearer '+token } }); if(res.ok) mutate(); else { const t = await res.text(); alert('Erro: '+t) } }
  return (<div className="min-h-screen"><TopNav /><main className="max-w-5xl mx-auto p-4"><h1 className="text-2xl font-bold text-brand-500">Usuários</h1>
    <div className="mt-4 p-4 bg-white rounded shadow"><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Login" className="w-full border p-2 rounded mb-2" /><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome" className="w-full border p-2 rounded mb-2" /><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha" className="w-full border p-2 rounded mb-2" /><select value={role} onChange={e=>setRole(e.target.value)} className="w-full border p-2 rounded mb-2"><option value="usuario">Usuário</option><option value="admin">Admin</option></select><button onClick={add} className="bg-brand-500 text-white rounded p-2">Adicionar Usuário</button></div>
    <div className="mt-4 bg-white p-4 rounded shadow">{data?.map(u=>(<div key={u.username} className="p-2 border-b flex justify-between items-center"><div><div className="font-medium">{u.name} <span className="text-xs text-gray-400">({u.username})</span></div><div className="text-sm text-gray-500">Perfil: {u.role}</div></div><div className="text-sm flex items-center gap-2">{myRole==='admin' && u.username!=='admin' && <button onClick={()=>remove(u.username)} className="text-red-600">Excluir</button>}<div className="text-xs text-gray-400">{u.username}</div></div></div>))}</div>
  </main></div>) }
